angular.module("openData")
	.constant("VERTICAL_BAR_CHART" 	 , 0)
	.constant("HORIZONTAL_BAR_CHART" , 1)
	.constant("PIE_CHART" 			 , 2)
	.constant("LINE_CHART" 			 , 3)
	.constant("AREA_CHART" 			 , 4)
	.constant("BUBBLE_CHART" 		 , 5)
	.constant("COMBO_BAR_LINE_CHART" , 6)